### ISSUE TITLE
Error on Xiaomi Redmi Note 4/X

### ISSUE THREAD

**Issue by eranbo** [pradeep1991singh/react-native-secure-key-store#14]
Hi,

I've tested the module with various of phones and it works on most of them except from Xiaomi Redmi Note 4.

Here is a link to a github repo of the app (Very simple POC for reading and writing one simple key,value)
https://github.com/eranbo/RNSS

Also attaching the ADB logcat and device software version information screen shot.

![xiaomi redmi note 4](https://user-images.githubusercontent.com/3517429/34366765-4eb5d42c-eaa9-11e7-9f94-2f05ce1264af.png)

[Xiaomi Redmi Note 4.log](https://github.com/pradeep1991singh/react-native-secure-key-store/files/1588040/Xiaomi.Redmi.Note.4.log)

Update: Tested it on Xiaomi Redmi Note 3 and it works as expected.
Thanks,
Eran

**Comment by tombailey** [comment]
The log you give suggests that no certificate exists for the alias provided. Perhaps we should change https://github.com/pradeep1991singh/react-native-secure-key-store/blob/master/android/src/main/java/com/reactlibrary/securekeystore/RNSecureKeyStoreModule.java#L69 to

`if (!keyStore.containsAlias(alias) || keyStore.getCertificate(alias) == null) {`

This explicitly checks for the alias in the keystore as well as a valid certificate; rather than just the former which is what we had before.

**Comment by tombailey** [comment]
@eranbo can you try https://github.com/pradeep1991singh/react-native-secure-key-store/pull/16

**Comment by eranbo** [comment]
Hi @tombailey 
sorry for the late response I got drawn into other things
Will give a try soon and update you

**Comment by eranbo** [comment]
Hi,
I've asked a colleague to give a try and test the new code.
It'w working.
Thank you all and I'm closing this issue.
Eran
